MySite/MySite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MySite/main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about_me', views.about_me, name='about_me'),
    path('my_projects', views.my_projects, name='projects'),
    path('my_projects/<slug:project_slug>', views.project_view, name='project'),
    path('order/', views.order_view, name='order'),
    path('ordered/', views.ordered, name='ordered'),
    path('actual_orders', views.actual_orders_view, name='orders_admin'),

]

MySite/users/urls.py
from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('log_out/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.user_profile, name='profile'),
    path('profile/edit_profile', views.edit_profile_view, name='edit_profile'),
]

MySite/main/models.py
from django.contrib.auth.models import User
from django.db import models


class Projects(models.Model):
    project_name = models.CharField(max_length=250, verbose_name='Название проекта',
                                    blank=True, null=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    date_added = models.DateTimeField(auto_now=True, verbose_name='Дата добавления')
    price = models.FloatField(verbose_name='Цена', blank=True, null=True)
    project_slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return self.project_name

    def get_absolute_url(self):
        return f'/my_projects/{self.project_slug}'

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class ProjectPhoto(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, verbose_name='Проект')
    photo = models.ImageField(verbose_name='Фото', upload_to='media/project_photo')

    def __str__(self):
        return self.project.project_name

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фото'


class Order(models.Model):
    theme = models.CharField(max_length=250, verbose_name='Тема')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    email = models.EmailField(max_length=100, verbose_name='Электронная почта')
    phone_number = models.CharField(verbose_name='Номер телефона')
    address = models.CharField(max_length=300, verbose_name='Адрес доставки')
    description = models.TextField(verbose_name='Описание заказа')
    photo = models.ImageField(upload_to='media/orderPhotos', verbose_name='Фото', null=True)

    def __str__(self):
        return self.theme

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

MySite/main/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    theme = forms.CharField(max_length=250, label='Тема')
    email = forms.EmailField(max_length=100, label='Электронная почта')
    phone_number = forms.CharField(max_length=250, label='Номер телефона')
    address = forms.CharField(max_length=300, label='Адрес доставки')
    description = forms.Textarea()
    photo = forms.ImageField(label='Фото')

    class Meta:
        model = Order
        fields = ['theme', 'email', 'phone_number', 'address', 'description', 'photo']

MySite/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.conf import settings
from django.core.mail import send_mail


def index(request):
    return render(request, 'main/index.html')


def about_me(request):
    return render(request, 'main/about_me.html')


def my_projects(request):
    projects = Projects.objects.order_by('-date_added')

    context = {'projects': projects}

    return render(request, 'main/my_projects.html', context)


def project_view(request, project_slug):
    project = Projects.objects.get(project_slug=project_slug)
    images = ProjectPhoto.objects.prefetch_related('project').filter(project=project.id)

    context = {'project': project, 'project_photo': images}

    return render(request, 'main/project.html', context)


@login_required(login_url='users:login')
def order_view(request):
    if request.method != 'POST':
        form = OrderForm()
    else:
        form = OrderForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.user = request.user
            form.save()
            send_mail('Заказ оформлен', f'Добрый день, {request.user.username}!\n'
                                        f'Ваш заказ {new_order} успешно оформлен. Администратор сайта скоро свяжется '
                                        f'с вами!', settings.EMAIL_HOST_USER, [new_order.email])
            send_mail('Новый заказ', f'Добрый день!\nНа сайте оформлен новый заказ.'
                                     f'\nПользователь: {request.user.username}\n'
                                     f'Номер телефона: {new_order.phone_number}\n'
                                     f'email: {new_order.email}\n'
                                     f'Адрес доставки: {new_order.address}\n'
                                     f'{new_order.theme}\n'
                                     f'{new_order.description}', settings.EMAIL_HOST_USER,
                      ['alekseev.i260303@gmail.com'])
            return redirect('main:ordered')

    context = {'form': form}
    return render(request, 'main/order.html', context)


@login_required(login_url='users:login')
def ordered(request):
    return render(request, 'main/ordered.html')


@login_required(login_url='users:login')
def actual_orders_view(request):
    orders = Order.objects.prefetch_related('user').order_by('-id')
    conntext = {'actual_orders': orders}
    return render(request, 'main/orders_admin.html', conntext)

MySite/main/templates/main/about_me.html
{% extends 'main/base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}Обо мне{% endblock %}

{% block page_header %}
    <h1>Обо мне</h1>

{% block content %}
    <h1>Напишите о себе</h1>

    <link rel="stylesheet" href="{% static 'main/css/about_me.css' %}">
{% endblock %}

MySite/main/templates/main/base.html
{% load django_bootstrap5 %}
{% load static %}

<!doctype html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>
            {% block title %}{% endblock %}
        </title>

        <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
        <link rel="icon" href="{% static 'main/images/icon/icon.jpeg' %}">

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4 border">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'main:index' %}" style="font-size: 24pt" onmouseover="this.style.color='#90EE90'"
                onmouseout="this.style.color='gold'">Главная</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="font-size: 14pt">
                        <li class="nav-item">
                            <a href="{% url 'main:about_me' %}" class="nav-link">Обо мне</a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'main:projects' %}" class="nav-link">Мои работы</a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'main:order' %}" class="nav-link">Заказать</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mr-auto" style="font-size: 14pt">
                        {% if user.is_authenticated %}
                            <span class="navbar-text" style="color: mediumspringgreen;"><strong>Здравствуйте, {{ user.username }}!</strong></span>
                            {% if user.is_superuser %}
                                <li class="nav-item">
                                    <a href="{% url 'main:orders_admin' %}" class="nav-link">Актуальные заказы</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">Управление</a>
                                </li>
                            {% else %}
                                {% if avatar %}
                                    <li class="nav-item">
                                       <img src="{{avatar.url}}" alt="user_avatar" width="60px" style="border-radius: 20px; margin-left: 7px;">
                                    </li>
                                {% else %}
                                    <li class="nav-item">
                                       <img src="{% static 'main/images/avatars/void_avatar.jpg' %}"
                                            alt="user_avatar" width="60px" style="border-radius: 20px; margin-left: 7px;">
                                    </li>
                                {% endif %}
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:profile' %}">Перейти в профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'users:login' %}">Войти</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="base">
                <div class="header pb-2 mb-2 border-bottom">
                    {% block page_header %}{% endblock %}
                </div>

                <div class="content">
                    {% block content %}{% endblock %}
                </div>

                <div class="footer">
                    <div style="float: left; margin-right: 15px">
                        <h6>По возникающим вопросам писать на почту
                            <br>или в телеграм</h6>
                        <div>example72@gmail.com</div>
                        <div><a href="#" style="color: white">User Userov</a></div>
                    </div>

                    <div style="float: left; margin-right: 15px">
                        <h6 style="text-align: left;  width: 135px">Чаты в соцсетях</h6>
                        <div style=" float: left; margin-right: 15px">
                            <a href="#" target="_blank">
                                <img src="{% static 'main/images/logo/img_1.png' %}" alt="" width="60px" height="60px">
                            </a>
                        </div>

                        <div style="margin-top: 5px;">
                            <a href="#" target="_blank">
                                <img src="{% static 'main/images/logo/img_2.png' %}"
                                     alt="" width="60px" height="60px">
                            </a>
                        </div>
                    </div>
                    <div style="float: left">
                        <h6>Сервер в Discord</h6>
                        <div style="margin-right: 15px; float: left">
                            <a href="#" target="_blank">
                                <img src="{% static 'main/images/logo/ds_logo.png' %}"
                                     alt="Discord" width="60px" height="60px">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        
        <div class="btn-up btn-up_hide"></div>
        <script src="{% static 'main/js/base.js' %}"></script>
    </body>
</html>

MySite/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block title %}Главная{% endblock %}

{% block page_header %}
    <h1>Главная страница</h1>
{% endblock %}

{% block content %}
    <h1>Разместите здесь содержание вашей главной страницы</h1>

    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
{% endblock %}

MySite/main/templates/main/my_projects.html
{% extends 'main/base.html' %}

{% block title %}Мои работы{% endblock %}

{% block content %}
    <h1>Мои работы</h1>
    <ul>
        {% for project in projects %}
            <li>
                <h4>Date added: {{project.date_added}}</h4>
                <a href="{% url 'main:project' project.project_slug %}">{{project}}</a>

            </li>
        {% empty %}
            <li>
                <h3>На данный момент нет проектов</h3>
            </li>
        {% endfor %}

    </ul>
{% endblock %}

MySite/main/templates/main/order.html
{% extends 'main/base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}Оформление заказа{% endblock %}

{% block page_header %}Оформление заказа{% endblock %}

{% block content %}
    <form action="{% url 'main:order' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Подтвердить" button_class="btn-success" %}
    </form>
    <input type="hidden" name="next" value="{% url 'main:index' %}">

    <link rel="stylesheet" href="{% static 'main/css/forms.css' %}">
{% endblock %}

MySite/main/templates/main/ordered.html
{% extends 'main/base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}Заказ оформлен{% endblock %}

{% block page_header %}
    <h1>Заказ оформлен</h1>
{% endblock %}

{% block content %}
    <div class="ordered_content">
        <h2>Спасибо за ваш заказ!</h2>
        <h3>Администратор сайта скоро свяжется с вами для уточнения деталей.</h3>
        <a href="{% url 'main:index' %}" class="btn btn-lg btn-success">Вернуться на сайт</a>
    </div>

    <link rel="stylesheet" href="{% static 'main/css/ordered.css' %}">
{% endblock %}

MySite/main/templates/main/orders_admin.html
{% extends 'main/base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}Актуальные заказы{% endblock %}

{% block page_header %}
    <h1>Актуальные заказы</h1>
{% endblock %}

{% block content %}
    {% for order in actual_orders %}
        <div class="order">
            <h2>{{order}}</h2>
            <h3>Заказчик: {{order.user.username}}</h3>
            <h3>ФИО: {{order.user.first_name}} {{order.user.last_name}}</h3>
            <h3>Телефон: {{order.phone_number}}</h3>
            <h3>Адрес электронной почты: {{order.email}}</h3>
            <h3>Пожелания пользователя:<br>{{order.description}}</h3>
            <h3>Фото:</h3>
            <img src="{{order.photo.url}}" alt="Фото заказа" width="600px" height="auto">
            <h3>Адрес доставки: {{order.address}}</h3>
        </div>
    {% empty %}
        <h2>На данный момент нет актуальных заказов</h2>
    {% endfor %}

    <link rel="stylesheet" href="{% static 'main/css/orders.css' %}">
{% endblock %}

MySite/main/templates/main/project.html
{% extends 'main/base.html' %}

{% block title %}{{project}}{% endblock %}

{% block content %}
    <h1>{{project}}</h1>
    <h4>Date added: {{project.date_added}}</h4>
    <p>
        <strong>Description</strong>
        <br>
        {{project.description}}
    </p>
    <p>Price: {{project.price}}$</p>
    <ul>
        {% for obj in project_photo %}
            <li><img src="{{obj.photo.url}}" alt="{{obj}}" width="600px"></li>
        {% endfor %}
    </ul>
{% endblock %}